In [1]:
import pandas as pd 
import requests

In [2]:
url='https://api.mfapi.in/mf/125497'
r=requests.get(url)
print(r.status_code)
data=r.json()

200

In [3]:
print(data.keys())

dict_keys(['meta', 'data', 'status'])

In [12]:
df = pd.DataFrame(data=data['data'])
df

            date        nav
0     01-06-2026  192.31950
1     31-05-2026  193.68360
2     29-05-2026  193.68480
3     27-05-2026  195.05010
4     26-05-2026  194.22580
...          ...        ...
3086  22-11-2013   12.77750
3087  21-11-2013   12.79570
3088  20-11-2013   12.95490
3089  19-11-2013   13.10680
3090  18-11-2013   13.08940

[3091 rows x 2 columns]

In [7]:
df.shape
df.dtypes

date    object
nav     object
dtype: object

In [8]:
df.head()

         date        nav
0  01-06-2026  192.31950
1  31-05-2026  193.68360
2  29-05-2026  193.68480
3  27-05-2026  195.05010
4  26-05-2026  194.22580

In [10]:
df.to_csv('api_data.csv', index=False)