In [1]:
import pandas as pd 
df=pd.read_csv('02_nav_history.csv')
df.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [2]:
import os 
print(os.getcwd())

c:\Users\h7743\Desktop\mutual funds analystics\data\raw

In [3]:
df.dtypes

amfi_code      int64
date          object
nav          float64
dtype: object

In [4]:
df['date']=pd.to_datetime(df['date'], format='%Y-%m-%d')
df['date'].head()

0   2022-01-03
1   2022-01-04
2   2022-01-05
3   2022-01-06
4   2022-01-07
Name: date, dtype: datetime64[ns]

In [5]:
df.dtypes

amfi_code             int64
date         datetime64[ns]
nav                 float64
dtype: object

In [6]:
df['date']=df['date'].sort_values()

In [7]:
df.head()

   amfi_code       date      nav
0     119551 2022-01-03  54.3856
1     119551 2022-01-04  54.3474
2     119551 2022-01-05  54.6869
3     119551 2022-01-06  55.4550
4     119551 2022-01-07  55.3692

In [8]:
df[df['nav'].isnull()]

Empty DataFrame
Columns: [amfi_code, date, nav]
Index: []

In [9]:
df['nav'].unique()

array([ 54.3856,  54.3474,  54.6869, ..., 288.8007, 280.6873, 279.7511],
      shape=(45594,))

In [10]:
len(df['nav'].isnull())

46000

In [11]:
len(df['nav'])

46000

In [12]:
df[df['nav']=='']

Empty DataFrame
Columns: [amfi_code, date, nav]
Index: []

In [13]:
#NAV column inspected.
#No null values found.
#No blank values found.Forward fill not required because NAV history is complete.

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.drop_duplicates(inplace=True)

In [16]:
df[df['nav']<=0]

Empty DataFrame
Columns: [amfi_code, date, nav]
Index: []

In [17]:
df['nav'].min()

np.float64(26.1366)

In [18]:
df.to_csv('../processed/nav_history_clean.csv', index=False)

In [19]:
import os

print(os.getcwd())
print(os.listdir())

c:\Users\h7743\Desktop\mutual funds analystics\data\raw
['01_fund_master.csv', '02_nav_history.csv', '03_aum_by_fund_house.csv', '04_monthly_sip_inflows.csv', '05_category_inflows.csv', '06_industry_folio_count.csv', '07_scheme_performance.csv', '08_investor_transactions.csv', '09_portfolio_holdings.csv', '10_benchmark_indices.csv', 'api_data.csv', 'api_data.ipynb', 'cleaning_data.ipynb', 'icici_bluechip.csv', 'inspection.ipynb', 'kotak_bluechip.csv', 'm_api_data.py', 'nippon_largecap.csv', 'sbi_bluechip.csv']

In [20]:
d=pd.read_csv('08_investor_transactions.csv')
d.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [21]:
d.dtypes

investor_id            object
transaction_date       object
amfi_code               int64
transaction_type       object
amount_inr              int64
state                  object
city                   object
city_tier              object
age_group              object
gender                 object
annual_income_lakh    float64
payment_mode           object
kyc_status             object
dtype: object

In [22]:
d['transaction_type'].unique()
#no unstandard transaction types found.

array(['SIP', 'Redemption', 'Lumpsum'], dtype=object)

In [23]:
d['amount_inr'].min()

np.int64(400)

In [24]:
d['amount_inr'].max()

np.int64(597498)

In [25]:
d.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [26]:
d.dtypes

investor_id            object
transaction_date       object
amfi_code               int64
transaction_type       object
amount_inr              int64
state                  object
city                   object
city_tier              object
age_group              object
gender                 object
annual_income_lakh    float64
payment_mode           object
kyc_status             object
dtype: object

In [27]:
d.dtypes

investor_id            object
transaction_date       object
amfi_code               int64
transaction_type       object
amount_inr              int64
state                  object
city                   object
city_tier              object
age_group              object
gender                 object
annual_income_lakh    float64
payment_mode           object
kyc_status             object
dtype: object

In [28]:
d['transaction_date']

0        2024-01-01
1        2024-01-01
2        2024-01-01
3        2024-01-01
4        2024-01-01
            ...
32773    2025-05-30
32774    2025-05-30
32775    2025-05-30
32776    2025-05-30
32777    2025-05-30
Name: transaction_date, Length: 32778, dtype: object

In [29]:
d['transaction_date']=pd.to_datetime(d['transaction_date'], format='%Y-%m-%d')

In [30]:
d.dtypes

investor_id                   object
transaction_date      datetime64[ns]
amfi_code                      int64
transaction_type              object
amount_inr                     int64
state                         object
city                          object
city_tier                     object
age_group                     object
gender                        object
annual_income_lakh           float64
payment_mode                  object
kyc_status                    object
dtype: object

In [31]:
d.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [33]:
d['kyc_status'].unique()

array(['Verified', 'Pending'], dtype=object)

In [34]:
d.drop_duplicates(inplace=True)

In [35]:
d.to_csv('../processed/processed_investor_transactions.csv', index=False)

In [36]:
f=pd.read_csv('07_scheme_performance.csv')
f.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [37]:
f.dtypes

amfi_code               int64
scheme_name            object
fund_house             object
category               object
plan                   object
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade             object
dtype: object

In [39]:
f['return_1yr_pct'].head()

0    12.42
1    15.25
2    24.56
3    20.59
4     5.34
Name: return_1yr_pct, dtype: float64

In [40]:
f['return_1yr_pct'].max()

np.float64(24.93)

In [41]:
f['return_1yr_pct'].min()

np.float64(4.26)

In [42]:
f['return_3yr_pct'].min()

np.float64(5.14)

In [43]:
f['return_3yr_pct'].max()

np.float64(23.39)

In [44]:
f['return_5yr_pct'].min()

np.float64(5.43)

In [47]:
f['return_5yr_pct'].max()

np.float64(23.8)

In [48]:
f['expense_ratio_pct'].min()

np.float64(0.55)

In [49]:
f['expense_ratio_pct'].max()

np.float64(1.64)

In [50]:
f.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [51]:
f['fund_house'].unique()

array(['SBI Mutual Fund', 'HDFC Mutual Fund', 'ICICI Prudential MF',
       'Nippon India MF', 'Kotak Mahindra MF', 'Axis Mutual Fund',
       'Aditya Birla Sun Life MF', 'UTI Mutual Fund', 'Mirae Asset MF',
       'DSP Mutual Fund'], dtype=object)

In [52]:
f['category'].unique()

array(['Large Cap', 'Small Cap', 'Gilt', 'Mid Cap', 'Short Duration',
       'Value', 'Liquid', 'Index/ETF', 'Flexi Cap', 'Index',
       'Large & Mid Cap', 'ELSS'], dtype=object)

In [53]:
f['plan'].unique()

array(['Regular', 'Direct'], dtype=object)

In [54]:
d.to_csv('../processed/processed_scheme_performance.csv', index=False)