In [1]:
import pandas as pd 
df1 = pd.read_csv("01_fund_master.csv")
df1.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [2]:
df1.shape

(40, 15)

In [3]:
df1.dtypes

amfi_code               int64
fund_house             object
scheme_name            object
category               object
sub_category           object
plan                   object
launch_date            object
benchmark              object
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager           object
risk_category          object
sebi_category_code     object
dtype: object

In [4]:
import os 
print(os.getcwd())

c:\Users\h7743\Desktop\mutual funds analystics\data\raw

In [5]:
df2 = pd.read_csv("02_nav_history.csv")
df2.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [6]:
df2.dtypes

amfi_code      int64
date          object
nav          float64
dtype: object

In [7]:
df2.shape

(46000, 3)

In [8]:
df3=pd.read_csv("03_aum_by_fund_house.csv")
df3.head()

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

In [9]:
df3.shape

(90, 5)

In [10]:
df3.dtypes

date               object
fund_house         object
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

In [11]:
df4=pd.read_csv("04_monthly_sip_inflows.csv")
df4.head()

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

In [12]:
df4.shape

(48, 6)

In [13]:
df4.dtypes

month                         object
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

In [14]:
df5=pd.read_csv("05_category_inflows.csv")
df5.head()

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

In [15]:
df5.shape

(144, 3)

In [16]:
df5.dtypes

month                object
category             object
net_inflow_crore    float64
dtype: object

In [17]:
df6=pd.read_csv("06_industry_folio_count.csv")
df6.head

<bound method NDFrame.head of       month  total_folios_crore  equity_folios_crore  debt_folios_crore  \
0   2022-01               13.26                 9.28               1.86
1   2022-04               13.91                 9.74               1.95
2   2022-07               13.85                 9.69               1.94
3   2022-10               14.12                 9.88               1.98
4   2023-01               14.81                10.37               2.07
5   2023-04               15.54                10.88               2.18
6   2023-07               16.28                11.40               2.28
7   2023-10               16.72                11.70               2.34
8   2024-01               17.78                12.45               2.49
9   2024-04               18.85                13.20               2.64
10  2024-07               19.98                13.99               2.80
11  2024-10               21.62                15.13               3.03
12  2024-12               22.89                16.02               3.20
13  2025-01               23.10                16.17               3.23
14  2025-03               23.45                16.42               3.28
15  2025-04               23.89                16.72               3.34
16  2025-07               24.57                17.20               3.44
17  2025-08               24.89                17.42               3.48
18  2025-09               25.19                17.63               3.53
19  2025-10               25.60                17.92               3.58
20  2025-12               26.12                18.28               3.66

    hybrid_folios_crore  others_folios_crore
0                  0.80                 1.33
1                  0.83                 1.39
2                  0.83                 1.38
3                  0.85                 1.41
4                  0.89                 1.48
5                  0.93                 1.55
6                  0.98                 1.63
7                  1.00                 1.67
8                  1.07                 1.78
9                  1.13                 1.89
10                 1.20                 2.00
11                 1.30                 2.16
12                 1.37                 2.29
13                 1.39                 2.31
14                 1.41                 2.35
15                 1.43                 2.39
16                 1.47                 2.46
17                 1.49                 2.49
18                 1.51                 2.52
19                 1.54                 2.56
20                 1.57                 2.61  >

In [18]:
df6.shape

(21, 6)

In [19]:
df6.dtypes

month                   object
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object

In [20]:
df7=pd.read_csv("07_scheme_performance.csv")
df7.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [21]:
df7.shape

(40, 19)

In [22]:
df7.dtypes

amfi_code               int64
scheme_name            object
fund_house             object
category               object
plan                   object
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade             object
dtype: object

In [23]:
df8=pd.read_csv("08_investor_transactions.csv")
df8.head

<bound method NDFrame.head of       investor_id transaction_date  amfi_code transaction_type  amount_inr  \
0       INV003054       2024-01-01     119092              SIP        1834
1       INV002952       2024-01-01     148567       Redemption      392882
2       INV003420       2024-01-01     118636              SIP         912
3       INV003436       2024-01-01     118634              SIP        1102
4       INV004691       2024-01-01     119094          Lumpsum        8682
...           ...              ...        ...              ...         ...
32773   INV003340       2025-05-30     101207          Lumpsum      168029
32774   INV001838       2025-05-30     119093              SIP        2175
32775   INV000074       2025-05-30     120504              SIP       25998
32776   INV002929       2025-05-30     148568              SIP         459
32777   INV001852       2025-05-30     118633       Redemption      226721

                state       city city_tier age_group  gender  \
0           Telangana  Hyderabad       T30       56+  Female
1              Punjab   Amritsar       B30     18-25    Male
2             Haryana  Faridabad       B30     36-45    Male
3         Maharashtra     Mumbai       T30     36-45  Female
4               Delhi      Noida       T30     26-35    Male
...               ...        ...       ...       ...     ...
32773  Madhya Pradesh     Indore       T30     26-35    Male
32774   Uttar Pradesh     Kanpur       B30     46-55    Male
32775       Rajasthan     Jaipur       T30     26-35  Female
32776     West Bengal    Kolkata       T30     26-35    Male
32777       Telangana  Hyderabad       T30     26-35    Male

       annual_income_lakh payment_mode kyc_status
0                    77.1          UPI   Verified
1                     7.1       Cheque   Verified
2                    47.2      Mandate   Verified
3                    54.4       Cheque    Pending
4                    14.5  Net Banking    Pending
...                   ...          ...        ...
32773                22.5  Net Banking   Verified
32774                27.6      Mandate   Verified
32775                 8.4          UPI   Verified
32776                13.0      Mandate   Verified
32777                21.7       Cheque   Verified

[32778 rows x 13 columns]>

In [24]:
df8.shape

(32778, 13)

In [25]:
df8.dtypes

investor_id            object
transaction_date       object
amfi_code               int64
transaction_type       object
amount_inr              int64
state                  object
city                   object
city_tier              object
age_group              object
gender                 object
annual_income_lakh    float64
payment_mode           object
kyc_status             object
dtype: object

In [26]:
df9=pd.read_csv("09_portfolio_holdings.csv")
df9.head

<bound method NDFrame.head of      amfi_code stock_symbol                 stock_name       sector  \
0       119551    POWERGRID     Power Grid Corporation    Utilities
1       119551     HDFCBANK              HDFC Bank Ltd      Banking
2       119551       GRASIM      Grasim Industries Ltd  Diversified
3       119551      DRREDDY   Dr. Reddy's Laboratories       Pharma
4       119551   ASIANPAINT           Asian Paints Ltd       Paints
..         ...          ...                        ...          ...
317     149324     DIVISLAB        Divi's Laboratories       Pharma
318     149324   BHARTIARTL          Bharti Airtel Ltd      Telecom
319     149324          TCS  Tata Consultancy Services           IT
320     149324   INDUSINDBK          IndusInd Bank Ltd      Banking
321     149324         NTPC                   NTPC Ltd    Utilities

     weight_pct  market_value_cr  current_price_inr portfolio_date
0         13.85           737.09            6011.08     2025-12-31
1         11.19            88.97            1074.65     2025-12-31
2          9.90           208.45            5964.59     2025-12-31
3          4.76           161.32            3748.82     2025-12-31
4         10.25           725.90            1321.45     2025-12-31
..          ...              ...                ...            ...
317        9.54           855.88            7453.05     2025-12-31
318        1.79           969.71             924.41     2025-12-31
319       13.17          1637.69            1927.89     2025-12-31
320        7.63          1387.30            3208.86     2025-12-31
321        2.04          1303.55            5797.95     2025-12-31

[322 rows x 8 columns]>

In [27]:
df9.shape

(322, 8)

In [28]:
df9.dtypes

amfi_code              int64
stock_symbol          object
stock_name            object
sector                object
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date        object
dtype: object

In [29]:
df10=pd.read_csv("10_benchmark_indices.csv")
df10.head

<bound method NDFrame.head of             date   index_name  close_value
0     2022-01-03      NIFTY50     17492.79
1     2022-01-04      NIFTY50     17689.64
2     2022-01-05      NIFTY50     17835.05
3     2022-01-06      NIFTY50     17878.51
4     2022-01-07      NIFTY50     17759.15
...          ...          ...          ...
8045  2026-05-25  CRISIL_GILT      2278.26
8046  2026-05-26  CRISIL_GILT      2281.42
8047  2026-05-27  CRISIL_GILT      2281.30
8048  2026-05-28  CRISIL_GILT      2298.35
8049  2026-05-29  CRISIL_GILT      2302.79

[8050 rows x 3 columns]>

In [30]:
df10.shape

(8050, 3)

In [31]:
df10.dtypes

date            object
index_name      object
close_value    float64
dtype: object

In [32]:
df1.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [33]:
df1['fund_house'].unique()

array(['SBI Mutual Fund', 'HDFC Mutual Fund', 'ICICI Prudential MF',
       'Nippon India MF', 'Kotak Mahindra MF', 'Axis Mutual Fund',
       'Aditya Birla Sun Life MF', 'UTI Mutual Fund', 'Mirae Asset MF',
       'DSP Mutual Fund'], dtype=object)

In [34]:
len(df1['scheme_name'].unique())

40

In [35]:
df1['category'].unique()

array(['Equity', 'Debt'], dtype=object)

In [36]:
df1['min_sip_amount'].mean()

np.float64(500.0)

In [37]:
df1['min_sip_amount'].unique()

array([500])

In [38]:
df1['amfi_code'].count()

np.int64(40)

In [39]:
len(df1['amfi_code'].unique())

40

In [40]:
df1.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [41]:
df2.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [42]:
df1['amfi_code'].count()

np.int64(40)

In [43]:
df2['amfi_code'].count()

np.int64(46000)

In [44]:
#slef written code
nl=[]
m=df1['amfi_code'].unique()
for n in df2['amfi_code'].unique() :
    if n in m:
        continue
    else:
        nl.append(n)
print(nl)

[]

In [45]:
#ai generted code
master_codes = set(df1['amfi_code'])

nav_codes = set(df2['amfi_code'])

missing_codes = nav_codes - master_codes

print(missing_codes)

set()

In [46]:
df1.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [47]:
df2.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [48]:
df3.head()

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

In [49]:
df4.head()

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

In [50]:
df5.head()

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

In [51]:
df6.head()

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

In [52]:
df7.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [53]:
df8.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [54]:
df9.head()

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

In [55]:
df10.head()

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15